# Build stage
FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN RUN VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8082/api} npm run build


# Runtime stage
FROM node:20-alpine
WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3000

ENV VITE_API_BASE_URL=http://localhost:8082/api

CMD ["serve", "-s", "dist", "-l", "3000"]